apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: mysql-pass
    literals:
        - password=abcd1234@1            #Change password as you want
resources:
  - mysql.yml 
  - wordpress.yml
